<?php

namespace Ikabalzam\LaravelXray\Support;

use Ikabalzam\LaravelXray\Constants;
use Illuminate\Support\Str;
use PhpParser\Node;

/**
 * Validates column references against the actual database schema and provides
 * developer-friendly fix suggestions.
 *
 * This class is the final gate in the audit pipeline: after a column name is
 * extracted and a table is resolved, ColumnValidator determines whether the
 * reference is valid, should be ignored, or is a genuine error worth reporting.
 *
 * Depends on SchemaRegistry for database schema lookups. The registry is
 * injected via constructor to allow testing with mock schemas.
 */
class ColumnValidator
{
    public function __construct(
        protected readonly SchemaRegistry $schemaRegistry
    ) {}

    /**
     * Check whether a column exists in the given table's schema.
     *
     * Returns true (valid) in the following cases:
     *   1. The table is not in the schema registry (can't validate what we don't know)
     *   2. The column exists directly in the table's column list
     *   3. The column looks like a pivot table foreign key — for belongsToMany
     *      relationships, columns like `user_id` may exist on the pivot table
     *      rather than the related table. We accept these if the column follows
     *      the `{singular_table}_id` pattern and exists anywhere in the schema.
     *
     * Edge case: Pivot table columns are tricky because the auditor resolves
     * the chain to the related model's table, but the query actually runs against
     * the pivot. Rather than trying to resolve pivot tables (which would require
     * deep relationship type tracking), we use the heuristic in case 3.
     *
     * @param  string  $column  The column name to validate (e.g., 'status', 'user_id').
     * @param  string  $table   The resolved table name (e.g., 'users', 'leads').
     * @return bool True if the column is valid or can't be disproven.
     */
    public function isValidColumn(string $column, string $table): bool
    {
        $tableColumns = $this->schemaRegistry->getTableColumns($table);

        if ($tableColumns === null) {
            return true; // Table not in schema, can't validate
        }

        if (in_array($column, $tableColumns)) {
            return true;
        }

        // For belongsToMany relationships, the column might be on the pivot table.
        // e.g., ->teamMembers()->where('user_id', ...) — user_id is on pivot, not users
        if (str_ends_with($column, '_id')) {
            $singularTable = Str::singular($table);
            if ($column === $singularTable . '_id' && $this->schemaRegistry->columnExistsAnywhere($column)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Check whether a column name matches any of the ignored patterns.
     *
     * Certain column names are dynamically generated by Eloquent and don't
     * correspond to real database columns. These include:
     *   - `*_count` — generated by `withCount()` (e.g., `jobs_count`)
     *   - `*_sum`, `*_avg`, etc. — generated by `withSum()`, `withAvg()`
     *   - `pivot_*` — pivot table attribute accessors
     *   - `laravel_*` — internal Laravel aliases
     *   - `preloaded_*` — preloaded aggregate aliases
     *
     * The patterns are defined in Constants::ignoredColumnPatterns() as regex.
     *
     * @param  string  $column  The column name to check.
     * @return bool True if the column matches an ignored pattern and should be skipped.
     */
    public function isIgnoredColumn(string $column): bool
    {
        foreach (Constants::ignoredColumnPatterns() as $pattern) {
            if (preg_match($pattern, $column)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Determine whether a column reference has an @audit-skip annotation.
     *
     * Developers can suppress audit warnings for intentional "violations" by
     * adding `@audit-skip` in three locations (checked in order):
     *
     *   1. **Inline comment on the same line:**
     *      `->where('legacy_col', $v) // @audit-skip`
     *
     *   2. **Comment on the line immediately above:**
     *      ```
     *      // @audit-skip — column exists in dynamic view
     *      ->where('computed_field', $value)
     *      ```
     *
     *   3. **PHPDoc on the enclosing method:**
     *      ```
     *      /** @audit-skip This method uses raw table not in schema * /
     *      public function legacyQuery() { ... }
     *      ```
     *      This skips ALL column references within the method.
     *
     * The method walks up the AST using the 'parent' attribute (set by
     * AstHelpers::setupParentReferences) to find the enclosing ClassMethod.
     *
     * @param  int    $lineNum  The 1-based line number of the column reference.
     * @param  array  $lines    The file contents as an array of lines (0-indexed).
     * @param  Node   $call     The AST node of the method call containing the column reference.
     * @return bool True if the reference should be skipped due to an @audit-skip annotation.
     */
    public function isAuditSkipped(int $lineNum, array $lines, Node $call): bool
    {
        // Check inline comment on the line itself: ->where('col', $v) // @audit-skip
        $line = $lines[$lineNum - 1] ?? '';
        if (preg_match('/@audit-skip/', $line)) {
            return true;
        }

        // Check the line above for a comment: // @audit-skip
        if ($lineNum >= 2) {
            $prevLine = trim($lines[$lineNum - 2] ?? '');
            if (preg_match('/@audit-skip/', $prevLine)) {
                return true;
            }
        }

        // Check enclosing method's PHPDoc
        $node = $call;
        while ($node = $node->getAttribute('parent')) {
            if ($node instanceof Node\Stmt\ClassMethod) {
                $doc = $node->getDocComment();
                if ($doc && str_contains($doc->getText(), '@audit-skip')) {
                    return true;
                }
                break;
            }
        }

        return false;
    }

    /**
     * Suggest the closest valid column name for a likely typo.
     *
     * Uses Levenshtein distance to find the best match among the table's actual
     * columns. Only suggests columns within an edit distance of 3, which covers
     * common typos like:
     *   - Transpositions: `stauts` → `status`
     *   - Missing characters: `statu` → `status`
     *   - Extra characters: `statuss` → `status`
     *   - Wrong characters: `statos` → `status`
     *
     * Returns null if no column is close enough, which avoids misleading
     * suggestions for completely wrong column names.
     *
     * @param  string  $typo   The invalid column name that was found.
     * @param  string  $table  The table to search for similar column names.
     * @return string|null A human-readable suggestion like "Did you mean 'status'?", or null.
     */
    public function suggestColumn(string $typo, string $table): ?string
    {
        $tableColumns = $this->schemaRegistry->getTableColumns($table);

        if ($tableColumns === null) {
            return null;
        }

        $bestMatch = null;
        $bestDistance = PHP_INT_MAX;

        foreach ($tableColumns as $validColumn) {
            $distance = levenshtein($typo, $validColumn);
            if ($distance < $bestDistance && $distance <= 3) {
                $bestDistance = $distance;
                $bestMatch = $validColumn;
            }
        }

        return $bestMatch ? "Did you mean '{$bestMatch}'?" : null;
    }
}
